<?php

declare(strict_types=1);

namespace FibBookingSystem\Tests\Integration\Document;

use Doctrine\DBAL\Connection;
use FibBookingSystem\Checkout\Document\BookingTicketRenderer;
use FibBookingSystem\Core\Domain\Ticket\BookingTicketService;
use FibBookingSystem\Core\Domain\Ticket\TicketDocumentService;
use PHPUnit\Framework\TestCase;
use Shopware\Core\Checkout\Cart\Price\Struct\CalculatedPrice;
use Shopware\Core\Checkout\Cart\Price\Struct\CartPrice;
use Shopware\Core\Checkout\Cart\Tax\Struct\CalculatedTaxCollection;
use Shopware\Core\Checkout\Cart\Tax\Struct\TaxRuleCollection;
use Shopware\Core\Checkout\Document\Renderer\DocumentRendererConfig;
use Shopware\Core\Checkout\Document\Service\DocumentGenerator;
use Shopware\Core\Checkout\Document\Service\HtmlRenderer;
use Shopware\Core\Checkout\Document\Struct\DocumentGenerateOperation;
use Shopware\Core\Defaults;
use Shopware\Core\Framework\Context;
use Shopware\Core\Framework\DataAbstractionLayer\Pricing\CashRoundingConfig;
use Shopware\Core\Framework\Test\TestCaseBase\KernelTestBehaviour;
use Shopware\Core\Framework\Uuid\Uuid;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Throwable;

/**
 * End-to-end ticket document pipeline against the real schema: order +
 * reservation + issued ticket → DocumentGenerator → readable PDF, and the
 * HTML variant proves the snippets actually resolve (no raw `fibBooking.…`
 * keys in the output — `|trans` falls back to the raw key, which is exactly
 * the bug this guards against).
 */
class TicketDocumentPdfTest extends TestCase
{
    use KernelTestBehaviour;

    private const RESOURCE_ID = 'f1b0000000000000000000000000c501';

    private Connection $connection;
    private Context $context;

    /** @var list<string> */
    private array $orderIds = [];

    protected function setUp(): void
    {
        $this->connection = self::container()->get(Connection::class);
        $this->context = Context::createDefaultContext();

        $this->cleanupBookingFixtures();
    }

    protected function tearDown(): void
    {
        $this->cleanupBookingFixtures();
        $this->cleanupOrders();
    }

    public function testIssuingATicketProducesAReadablePdfDocument(): void
    {
        $orderId = $this->seedOrder();
        $this->seedReservationWithTicket($orderId);

        // BookingTicketDocumentSubscriber generates the document as a side
        // effect of issueTicket — the order must already have one.
        $autoGenerated = $this->connection->fetchOne(
            <<<'SQL'
                SELECT COUNT(id) FROM document
                WHERE order_id = :orderId
                AND document_type_id = (SELECT id FROM document_type WHERE technical_name = 'fib_booking_ticket')
                SQL,
            ['orderId' => Uuid::fromHexToBytes($orderId)],
        );
        static::assertSame('1', (string) $autoGenerated, 'issuing a ticket must auto-generate the ticket document');

        /** @var TicketDocumentService $documentService */
        $documentService = self::container()->get(TicketDocumentService::class);

        // Idempotent repeat for the same ticket set: must return the existing
        // document, never a silent null (regression: duplicate document
        // number used to swallow the result).
        $documentId = $documentService->generateForOrder($orderId, $this->context);
        static::assertNotNull($documentId, 'repeat generation must answer with the existing document');

        $rendered = $documentService->getOrderTicketPdf($orderId, $this->context);
        static::assertNotNull($rendered);

        $content = $rendered->getContent();
        static::assertStringStartsWith('%PDF', $content, 'rendered document must be a real PDF');
        static::assertGreaterThan(1000, strlen($content), 'a one-ticket PDF with QR code cannot be near-empty');
    }

    public function testHtmlVariantResolvesSnippetsAndEmbedsTheQrCode(): void
    {
        $orderId = $this->seedOrder();
        $ticketNumber = $this->seedReservationWithTicket($orderId);

        // The renderer directly (no media persistence): the HTML output is
        // where raw snippet keys would surface.
        /** @var BookingTicketRenderer $renderer */
        $renderer = self::container()->get(BookingTicketRenderer::class);

        $operation = new DocumentGenerateOperation(
            $orderId,
            HtmlRenderer::FILE_EXTENSION,
            ['fileTypes' => [HtmlRenderer::FILE_EXTENSION]],
        );

        $result = $renderer->render([$orderId => $operation], $this->context, new DocumentRendererConfig());

        static::assertSame([], array_map(static fn (Throwable $e): string => $e->getMessage(), $result->getErrors()));
        $rendered = $result->getOrderSuccess($orderId);
        static::assertNotNull($rendered);
        $html = $rendered->getContent();

        // Snippets resolved (system language en-GB) — never raw keys.
        static::assertStringNotContainsString('fibBooking.document.', $html, 'raw snippet keys in the document mean the snippet files do not cover the template');
        static::assertStringContainsString('Please present the QR code at the entrance.', $html);
        static::assertStringContainsString('Booking', $html);

        // Ticket substance: number, booking number, embedded QR PNG.
        static::assertStringContainsString($ticketNumber, $html);
        static::assertStringContainsString('B-PDF-TEST', $html);
        static::assertStringContainsString('data:image/png;base64,', $html, 'QR code must be embedded as data URI');
    }

    public function testOrderWithoutTicketsFailsLoudly(): void
    {
        $orderId = $this->seedOrder();

        /** @var DocumentGenerator $generator */
        $generator = self::container()->get(DocumentGenerator::class);

        $result = $generator->generate(
            BookingTicketRenderer::TYPE,
            [$orderId => new DocumentGenerateOperation($orderId)],
            $this->context,
        );

        static::assertNull($result->getSuccess()->first());
        static::assertArrayHasKey($orderId, $result->getErrors(), 'no tickets must be an explicit error, not an empty PDF');
    }

    /**
     * Minimal order satisfying the order definition; lookups (sales channel,
     * country, salutation) come from the live schema instead of Shopware's
     * test fixtures, because this suite runs against the dev database.
     */
    private function seedOrder(): string
    {
        $orderId = Uuid::randomHex();
        $this->orderIds[] = $orderId;
        $addressId = Uuid::randomHex();

        $salesChannelId = $this->fetchHexId('SELECT LOWER(HEX(id)) FROM sales_channel WHERE active = 1 LIMIT 1');
        $countryId = $this->fetchHexId('SELECT LOWER(HEX(id)) FROM country WHERE active = 1 LIMIT 1');
        $salutationId = $this->fetchHexId('SELECT LOWER(HEX(id)) FROM salutation LIMIT 1');

        $rounding = json_decode((string) json_encode(new CashRoundingConfig(2, 0.01, true), \JSON_THROW_ON_ERROR), true, 512, \JSON_THROW_ON_ERROR);

        self::container()->get('order.repository')->create([
            [
                'id' => $orderId,
                'orderNumber' => 'FIB-PDF-' . Uuid::randomHex(),
                'salesChannelId' => $salesChannelId,
                'languageId' => Defaults::LANGUAGE_SYSTEM,
                'currencyId' => Defaults::CURRENCY,
                'currencyFactor' => 1.0,
                'orderDateTime' => '2026-06-01 10:00:00.000',
                'stateId' => $this->fetchHexId(
                    <<<'SQL'
                        SELECT LOWER(HEX(state.id)) FROM state_machine_state state
                        INNER JOIN state_machine machine ON machine.id = state.state_machine_id
                        WHERE machine.technical_name = 'order.state' AND state.technical_name = 'open'
                        SQL,
                ),
                'price' => new CartPrice(10, 10, 10, new CalculatedTaxCollection(), new TaxRuleCollection(), CartPrice::TAX_STATE_GROSS),
                'shippingCosts' => new CalculatedPrice(0, 0, new CalculatedTaxCollection(), new TaxRuleCollection()),
                'itemRounding' => $rounding,
                'totalRounding' => $rounding,
                'billingAddressId' => $addressId,
                'addresses' => [
                    [
                        'id' => $addressId,
                        'salutationId' => $salutationId,
                        'firstName' => 'Erika',
                        'lastName' => 'Musterfrau',
                        'street' => 'Musterstraße 1',
                        'zipcode' => '12345',
                        'city' => 'Musterstadt',
                        'countryId' => $countryId,
                    ],
                ],
                'orderCustomer' => [
                    'email' => 'ticket-pdf-test@example.com',
                    'firstName' => 'Erika',
                    'lastName' => 'Musterfrau',
                    'salutationId' => $salutationId,
                    'customerNumber' => 'FIB-PDF-TEST',
                ],
            ],
        ], $this->context);

        return $orderId;
    }

    /**
     * @return string the issued ticket number
     */
    private function seedReservationWithTicket(string $orderId): string
    {
        $reservationId = Uuid::randomHex();

        $this->connection->executeStatement(
            <<<'SQL'
                INSERT INTO fib_booking_resource (id, name, technical_name, capacity, active, created_at)
                VALUES (:id, 'PDF Test Resource', 'fib_test_pdf_resource', 10, 1, NOW(3))
                SQL,
            ['id' => Uuid::fromHexToBytes(self::RESOURCE_ID)],
        );

        $this->connection->executeStatement(
            <<<'SQL'
                INSERT INTO fib_booking_reservation
                    (id, resource_id, order_id, order_version_id, booking_number, starts_at, ends_at, quantity, status, created_at)
                VALUES
                    (:id, :resourceId, :orderId, :orderVersionId, 'B-PDF-TEST', '2026-12-01 18:00:00.000', '2026-12-01 20:00:00.000', 1, 'confirmed', NOW(3))
                SQL,
            [
                'id' => Uuid::fromHexToBytes($reservationId),
                'resourceId' => Uuid::fromHexToBytes(self::RESOURCE_ID),
                'orderId' => Uuid::fromHexToBytes($orderId),
                'orderVersionId' => Uuid::fromHexToBytes(Defaults::LIVE_VERSION),
            ],
        );

        /** @var BookingTicketService $ticketService */
        $ticketService = self::container()->get(BookingTicketService::class);

        return $ticketService->issueTicket($reservationId, $this->context)->getTicketNumber();
    }

    private function fetchHexId(string $sql): string
    {
        $id = $this->connection->fetchOne($sql);
        static::assertIsString($id, sprintf('lookup failed: %s', $sql));

        return $id;
    }

    private static function container(): ContainerInterface
    {
        $container = static::getKernel()->getContainer();

        return $container->has('test.service_container') ? $container->get('test.service_container') : $container;
    }

    private function cleanupBookingFixtures(): void
    {
        $resourceIdBytes = Uuid::fromHexToBytes(self::RESOURCE_ID);

        $this->connection->executeStatement(
            <<<'SQL'
                DELETE log FROM fib_booking_scan_log log
                INNER JOIN fib_booking_ticket ticket ON ticket.id = log.ticket_id
                INNER JOIN fib_booking_reservation reservation ON reservation.id = ticket.reservation_id
                WHERE reservation.resource_id = :resourceId
                SQL,
            ['resourceId' => $resourceIdBytes],
        );
        $this->connection->executeStatement(
            <<<'SQL'
                DELETE ticket FROM fib_booking_ticket ticket
                INNER JOIN fib_booking_reservation reservation ON reservation.id = ticket.reservation_id
                WHERE reservation.resource_id = :resourceId
                SQL,
            ['resourceId' => $resourceIdBytes],
        );
        $this->connection->executeStatement(
            'DELETE FROM fib_booking_reservation WHERE resource_id = :resourceId',
            ['resourceId' => $resourceIdBytes],
        );
        $this->connection->executeStatement(
            'DELETE FROM fib_booking_resource WHERE id = :id',
            ['id' => $resourceIdBytes],
        );
    }

    /**
     * Deletes generated documents (incl. their media) and the order across
     * ALL versions — document generation freezes the order into an extra
     * version that a plain DAL live-version delete would leave behind.
     */
    private function cleanupOrders(): void
    {
        foreach ($this->orderIds as $orderId) {
            $orderIdBytes = Uuid::fromHexToBytes($orderId);

            /** @var list<string> $mediaIds */
            $mediaIds = $this->connection->fetchFirstColumn(
                'SELECT LOWER(HEX(document_media_file_id)) FROM document WHERE order_id = :orderId AND document_media_file_id IS NOT NULL',
                ['orderId' => $orderIdBytes],
            );

            $this->connection->executeStatement('DELETE FROM document WHERE order_id = :orderId', ['orderId' => $orderIdBytes]);

            if ($mediaIds !== []) {
                self::container()->get('media.repository')->delete(
                    array_map(static fn (string $id): array => ['id' => $id], $mediaIds),
                    $this->context,
                );
            }

            // Children (order_customer, order_address, …) cascade via FK.
            $this->connection->executeStatement('DELETE FROM `order` WHERE id = :orderId', ['orderId' => $orderIdBytes]);
        }

        $this->orderIds = [];
    }
}
